package thyscom.eulersolutions;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * 
 * Answer: 4613732
 * 
 */
public class E2 {

	int MAX = 4000000;

	public static void main(String[] args) {
		E2 e2 = new E2();
		System.out.println(e2.testfind());
		System.out.println(e2.smarterFind());
	}

	/**
	 * a,b,c,a,b,c,a,b,c only c are even
	 * 
	 * @return
	 */
	private int smarterFind() {
		int a = 1;
		int b = 1;
		int c = a + b;
		int sum = 0;

		while (c < MAX) {
			sum += c;
			a = b + c;
			b = c + a;
			c = a + b;
		}
		return sum;
	}

	/**
	 * a,b,a,b,....
	 * 
	 * @return
	 */
	private int testfind() {
		int sum = 0;
		int a = 1;
		int b = 1;
		int tmp = 0;

		while (b < MAX) {
			if (b % 2 == 0) {
				sum += b;
			}
			tmp = a + b;
			a = b;
			b = tmp;
		}
		return sum;
	}
}
