package thyscom.eulersolutions;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * 
 * @author thysmeintjes
 */
public class E2 {
	public static void main(String[] args) {
		E2 e2 = new E2();
		System.out.println(e2.find());
	}

	private int find() {
		int total = 0;
		int previousFib = 1;
		int currentFib = 2;
		int tmp = 0;
		
		while (currentFib < 4000000) {
			if (currentFib % 2 == 0) {
				total += currentFib;
			}
			tmp = previousFib;
			previousFib = currentFib;
			currentFib += tmp;
		}
		return total;
	}
}
